modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL="https://github.com/GreenhouseTeam/reloadable-datapack-registries/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "https://github.com/GreenhouseTeam/reloadable-datapack-registries"
logoFile = "${mod_id}.png"
authors = "Greenhouse Team, MerchantPug"
description = '''${description}'''

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[mods]]
modId = "rdprtestmod"
version = "${version}"
displayName = "Reloadable Data Pack Registries Testmod"
displayURL = "https://github.com/GreenhouseTeam/reloadable-datapack-registries"
authors = "MerchantPug"
description = '''Reloadable Datapack Registries Testmod'''

[[dependencies.rdprtestmod]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.rdprtestmod]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.rdprtestmod]]
modId = "${mod_id}"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "BOTH"