modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="${mod_id}.png" #optional
authors = "Greenhouse Team, MerchantPug" #optional
description = '''${description}''' #mandatory (Supports multiline text)

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"